project:
  type: website
  output-dir: docs

website:
  title: "Template"
  
  navbar:
    left:
      - text: Template
        href: index.qmd
        
    right:
      - icon: github
        href: https://github.com/
    search: true
    
format:
  html:
    theme: cosmo
    relative-resources: true
    css: styles/tooltip.css
    csl: styles/nuclear-medicine-and-molecular-imaging.csl
    toc: true
    toc-depth: 4
    include-after-body:
    #   - text: |
    #       <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js""></script>
      - text: |
          <script src="/scripts/tooltip.js"></script>
    
    comments:
      utterances:
        repo: RadiationSafetyNM/website